# Generated by Django 3.2.7 on 2021-09-23 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compte', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='genre',
            field=models.CharField(max_length=15),
        ),
    ]
