# Generated by Django 3.2.6 on 2021-10-07 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compte', '0002_alter_client_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='commentaire',
            field=models.CharField(default=4, max_length=150),
            preserve_default=False,
        ),
    ]
