# Generated by Django 3.2.6 on 2021-10-07 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compte', '0003_client_commentaire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='commentaire',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
