# Generated by Django 3.2.6 on 2021-10-07 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compte', '0004_alter_client_commentaire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='commentaire',
            field=models.CharField(blank=True, default=8, max_length=150),
            preserve_default=False,
        ),
    ]
