# Generated by Django 3.2.6 on 2021-10-07 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compte', '0006_remove_client_commentaire'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='commentaire',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
    ]
