# Generated by Django 3.2.6 on 2021-10-21 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compte', '0007_client_commentaire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='genre',
            field=models.CharField(choices=[('Homme', 'Homme'), ('Femme', 'Femme'), ('Autre', 'Autre')], max_length=15),
        ),
    ]
