# Generated by Django 3.2.7 on 2021-10-22 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compte', '0008_alter_client_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='telephone',
            field=models.PositiveIntegerField(max_length=12),
        ),
    ]
