# Generated by Django 4.0.1 on 2022-01-25 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compte', '0010_alter_client_commentaire_alter_client_telephone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='telephone',
            field=models.IntegerField(),
        ),
    ]
