# Generated by Django 3.2.7 on 2021-10-21 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='prénom',
        ),
    ]
