# Generated by Django 3.2.6 on 2021-10-08 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parametres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stockMinPVente', models.IntegerField()),
                ('prixLivraison', models.IntegerField()),
                ('telephone', models.IntegerField()),
                ('adresse', models.CharField(max_length=15)),
                ('nomSalon', models.CharField(max_length=150)),
            ],
        ),
    ]
