# Generated by Django 3.2.7 on 2021-10-13 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametres', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parametres',
            name='adresse',
            field=models.CharField(max_length=30),
        ),
    ]
