# Generated by Django 3.2.6 on 2021-10-12 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametres', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametres',
            name='mail',
            field=models.CharField(default=2, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='parametres',
            name='adresse',
            field=models.CharField(max_length=30),
        ),
    ]
