# Generated by Django 3.2.6 on 2021-10-14 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parametres', '0002_alter_parametres_adresse'),
        ('parametres', '0003_parametres_codepostal'),
    ]

    operations = [
    ]
