# Generated by Django 3.2.6 on 2021-10-14 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametres', '0004_merge_20211014_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parametres',
            name='codePostal',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='parametres',
            name='telephone',
            field=models.CharField(max_length=100),
        ),
    ]
