# Generated by Django 3.2.5 on 2021-10-14 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parametres', '0004_merge_20211014_0910'),
        ('parametres', '0005_auto_20211014_1630'),
    ]

    operations = [
    ]
