# Generated by Django 3.2.6 on 2021-10-18 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parametres', '0006_merge_20211014_1822'),
        ('parametres', '0006_merge_20211015_0922'),
    ]

    operations = [
    ]
