# Generated by Django 3.2.5 on 2021-10-15 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametres', '0006_merge_20211014_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parametres',
            name='prixLivraison',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='parametres',
            name='stockMinPVente',
            field=models.PositiveIntegerField(),
        ),
    ]
