# Generated by Django 3.2.7 on 2021-10-18 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametres', '0007_merge_20211018_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parametres',
            name='prixLivraison',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='parametres',
            name='stockMinPVente',
            field=models.PositiveIntegerField(),
        ),
    ]
