# Generated by Django 3.2.7 on 2021-10-18 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parametres', '0007_auto_20211015_1129'),
        ('parametres', '0008_auto_20211018_1002'),
        ('parametres', '0008_auto_20211018_1439'),
    ]

    operations = [
    ]
