# Generated by Django 3.2.7 on 2021-10-22 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_auto_20211022_1004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='heure',
            field=models.TimeField(blank=True, choices=[('08:00:00', '08:00'), ('08:30:00', '08:30'), ('09:00:00', '09:00'), ('09:30:00', '09:30'), ('10:00:00', '10:00'), ('10:30:00', '10:30'), ('11:00:00', '11:00'), ('11:30:00', '11:30'), ('12:00:00', '12:00'), ('12:30:00', '12:30'), ('13:00:00', '13:00'), ('13:30:00', '13:30'), ('14:00:00', '14:00'), ('14:30:00', '14:30'), ('15:00:00', '15:00'), ('15:30:00', '15:30'), ('16:00:00', '16:00'), ('16:30:00', '16:30'), ('17:30:00', '17:30')], null=True, verbose_name='Heure: HH:MM (H+1)'),
        ),
    ]
