# Generated by Django 4.0.1 on 2022-01-25 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0004_alter_reservation_heure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestation',
            name='nom',
            field=models.CharField(default='', max_length=60),
        ),
        migrations.AddConstraint(
            model_name='prestation',
            constraint=models.UniqueConstraint(fields=('nom', 'pour'), name='prestation_unique'),
        ),
    ]
