# Generated by Django 3.2.7 on 2021-09-27 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=250)),
                ('type', models.CharField(max_length=250)),
                ('image', models.ImageField(upload_to='')),
                ('capacite', models.IntegerField()),
                ('statut', models.CharField(max_length=250)),
            ],
        ),
    ]
