# Generated by Django 3.2.7 on 2021-09-27 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produits', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produit',
            name='image',
        ),
    ]
