# Generated by Django 3.2.6 on 2021-09-30 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produits', '0002_remove_produit_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='quantite',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
