# Generated by Django 3.2.6 on 2021-09-30 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produits', '0003_produit_quantite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='quantite',
            field=models.IntegerField(),
        ),
    ]
