# Generated by Django 3.2.7 on 2021-10-01 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produits', '0004_alter_produit_quantite'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='prixAchat',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produit',
            name='prixVente',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
