# Generated by Django 3.2.7 on 2021-10-01 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produits', '0005_auto_20211001_1407'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produit',
            old_name='prixAchat',
            new_name='prix_achat',
        ),
        migrations.RenameField(
            model_name='produit',
            old_name='prixVente',
            new_name='prix_vente',
        ),
    ]
