# Generated by Django 3.2.7 on 2021-10-13 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produits', '0006_auto_20211001_1454'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='categorie',
            field=models.CharField(default=2, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produit',
            name='image',
            field=models.ImageField(default=2, upload_to=''),
            preserve_default=False,
        ),
    ]
