# Generated by Django 3.2.6 on 2021-10-18 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produits', '0008_alter_produit_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='prix_achat',
            field=models.IntegerField(verbose_name=1000),
        ),
        migrations.AlterField(
            model_name='produit',
            name='prix_vente',
            field=models.IntegerField(verbose_name=1000),
        ),
    ]
