# Generated by Django 3.2.7 on 2021-10-21 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produits', '0010_auto_20211018_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='prix_achat',
            field=models.DecimalField(decimal_places=2, max_digits=2),
        ),
        migrations.AlterField(
            model_name='produit',
            name='prix_vente',
            field=models.DecimalField(decimal_places=2, max_digits=2),
        ),
    ]
