# Generated by Django 3.2.7 on 2021-10-21 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produits', '0011_auto_20211021_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='prix_achat',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='produit',
            name='prix_vente',
            field=models.IntegerField(default=0),
        ),
    ]
