# Generated by Django 3.2.6 on 2021-10-21 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produits', '0012_auto_20211021_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='categorie',
            field=models.CharField(choices=[('Colorés', 'Colorés'), ('Permanantés', 'Permanantés'), ('Endommagés', 'Endommagés'), ('Fins Affaiblis', 'Fins Affaiblis'), ('Normaux sains', 'Normaux sains'), ('White Silver', 'White Silver'), ('Cocoa Brown', 'Cocoa Brown'), ('Coral Red', 'Coral Red'), ('Saffron Copper', 'Saffron Copper'), ('Violet Lavender', 'Violet Lavender'), ('Cheveux Stressés', 'Cheveux Stressés'), ('En profondeur', 'En profondeur')], max_length=250),
        ),
        migrations.AlterField(
            model_name='produit',
            name='type',
            field=models.CharField(choices=[('Shampoo', 'Shampoo'), ('Conditioner', 'Conditioner'), ('Treatment', 'Treatment'), ('Travel Pack', 'Travel Pack'), ('Protector', 'Protector'), ('Cream', 'Cream'), ('Drops', 'Drops'), ('Balm', 'Balm'), ('Mist', 'Mist'), ('Hydra Oil', 'Hydra Oil'), ('Oil', 'Oil'), ('Mask', 'Mask'), ('Serum', 'Serum')], max_length=250),
        ),
    ]
